version: "3"
services:
  front:
    container_name: time-management-app
    build:
      context: .
    environment:
      - NODE_ENV=development
    # volumes:
    #   - .:/app
    ports:
      - "3000:3000"
    tty: true
    # working_dir:
    #   /app/time-management-app